<template>
    <div class="text-xl ml-4 mr-4 border-4 border-indigo-900 rounded md:ml-12 md:mr-12 lg:ml-64 lg:mr-64">
        <h1 class="definitioncard">Was ist Kulturökologie?</h1>
        <p class="p-4 lg:p-8">
            Kulturökologie ist ein Bezugsrahmen zur kritischen Beschreibung und Bewertung von Kulturereignissen wie Bildung und Lernen in unserer ökonomisierten Gesellschaft
        </p>
        <ul class="p-4 lg:p-8">
            <li>im Prozess der Detraditionalisierung von Kultur</li>
            <li class="mt-4">in einem System individualisierter, digitaler, mobiler und konvergenter Medien und neuer digitaler Repräsentationsformen</li>
            <li class="mt-4">mit Bildung und Lernen als individualisiertem sozialen Risiko mit Risikolerner/innen</li>
            <li class="mt-4">in der Wissensgesellschaft mit Lernen als überprüfbarer und verwertbare Kulturressource. </li>
        </ul>
        <p class="p-4 lg:p-8">
            Kulturökologie ist ein ganzheitlich aufgebauter theoretischer Bezugsrahmen zur kritischen Beschreibung kultureller Veränderungen in der Dynamik unserer disparaten Kultur. Dazu gehört, dass Kulturökologie sich auch mit der kritischen Beschreibung und Bewertung von Bildung und Lernen in unserer ökonomisierten Gesellschaft beschäftigt. Stichwort dazu ist Wissensgesellschaft. Weil Kompetenzen, Wissen, Lernen Ressourcen der ökonomisch ausgerichteten Wissensgesellschaft sind, heißt das noch lange nicht, nun auch ökonomische Bewertungskriterien anzuwenden: möglichst viel, möglichst individualisiert und flexibel, alles geprüft und zertifiziert. In den anhaltenden Prozessen der Detraditionalisierung des Lernens wurde Lernen auch zu einem individualisierten sozialen Risiko mit Risikolernern, was zur Frage nach sozialer Gerechtigkeit als Kriterium einer Kulturökologie führt. Das ist eine Frage und Denklinie, die der u.a. mit dem Friedenspreis des deutschen Buchhandels ausgezeichnete amerikanisch indische Soziologe Amartya Sen deutlich gemacht hat.
        </p>
        <p class="p-4 lg:p-8">
            Kulturökologie versucht einen Rahmen für kritische Frage und für Kriterien zu formulieren, bei denen die Menschen mit ihren Entwicklungs- und Bildungsmöglichkeiten im Mittelpunkt stehen. Dabei ist der Blick auf die Bildungsideen der europäischen Aufklärung ausgesprochen anregend. Die Kerngedanken des jungen Wilhelm von Humboldt zu Bildung von 1792 bieten Denkanregungen auch für unsere digitale Konsum- und Medien/Internet/App-Welt: Bildung als Entfaltung der Kräfte der Kinder in der Aneignung und Gestaltung der digital ausgerichteten kulturellen Umwelt.
        </p>
        <p class="p-4 lg:p-8">
            Kulturökologie ist mit ideologischen Risken aufgeladen. Dazu gehört die Denkweise in ganzheitlichen Systemen, die ausschließt, dass sich Systeme überlagern, durchdringen, ergänzen. Zu den ideologischen Risken gehört, Neues auszugrenzen und das erfolgreich Bewährte als das Gültige anzusehen. In seiner Medienökologie stellte z.B. Neil Postman in den 1980er Jahren fest, dass Fernsehen Kindheit zum Verschwinden bringt: „The Disapperance of Childhood. (New York, Delacorte Press, 1982; Frankfurt a.M., S. Fischer 1983) und wir uns fernsehbedingt zu Tode amüsieren: „Amusing Ourselves to Death. Public Discourse in the Age of Show Business. (New York, Penguin Books 1985; Frankfurt a.M., S. Fischer 1985). Aktuell schließt Schule das Handy aus, obwohl es das wesentliche und globale mobile Endgeräte des Alltags ist. Ist das kulturökologisch zu begründen?
        </p>
        <p class="p-4 lg:p-8">
            Ein wesentliches Strukturelement der Wissensgesellschaft ist, Bildung in die Logik der Ökonomie einzuordnen und Bildung als verfügbare Ressource zu nutzen. Wie geht Pädagogik mit Bildung, Lernen, Wissen als verfügbare Ressourcen um? Hier ist die Tradition der Ökologie anregend, die sich mit der Nutzung von Natur und Energie als verfügbaren, überprüfbaren und verwertbaren Ressourcen kritisch auseinandersetzt. So entstand in den 1970er/ 80er Jahre eine Ökologie-Bewegung, u.a. weil Erdöl knapp wurde. Mit Ökologie als Ressourcen-Frage lassen sich die kulturellen Ressourcen Wissen, Lernen, Bildung in unserer ökonomisierten Gesellschaft erörtern. Die Kulturressourcen Wissen, Lernen, Bildung sind in der augenblicklichen Innovationsphase von Schule und Bildung verbunden mit Digitalisierung und ihren Medien sowie mit weiteren Repräsentationsformen der Digitalisierung wie die von Nutzern generierten Kontexten. Pädagogische Kriterien mit Blick auf Kulturressourcen sind zum einen Nachhaltigkeit/ Sustainability der Entwicklung von Kindern, Jugendlichen, Erwachsenen und ihrer Bildungsprozesse. Ein und vor allem didaktisches Kriterium ist das der Passung/ Affordance der didaktischen Angebote zur Bildung, also der Passung/ Affordance im und zum Prozess der Entwicklung der Lernenden. Zudem ist das Kriterium der sozialen Gerechtigkeit und der Partizipation wesentlich. Die angestammten pädagogischen Überlegungen zur Literacy oder zur Medienkompetenz gilt es zu erweitern, u.a. weil von Nutzern generierte Kontexte neue und alltägliche Ereignisse sind, die sich der einfachen pädagogischen und didaktischen Lösung der Kompetenz-Vermittlung entziehen. Konkrete wird das, wenn es z.B. um digitale Spiele oder Selfies mit Mobilen Endgeräten als von Nutzern generierte Kontexte geht.
            Zur Zeit scheint es schon fast selbstverständlich, die ökonomischen Kriterien der Effizienz und der Kontrolle auf den Erwerb von Wissen, das heißt auch, auf Lernen und Schule anzuwenden. Der aktuelle Trend der Didaktik zur Metrifizierung des Lernens und der vermessenden Lernanalyse (Learning Analytics) folgt dieser Logik. Hier kann man fragen, welche Rolle dabei medial und digital ausgerichtete Lehr- und Lernstrategien spielen. Was ist zudem mit digitalen Lernumgebungen im Internet oder mit den Alltagskontexten von Smartphones und ihren Apps? Die theoretische Diskussion läuft über den Gedanken der sozialsemiotischen Kontexte, die nutzergeneriert entstehen. So gesehen bekommt Pädagogik die Gestaltungsaufgabe für nutzergenerierte Lernkontexte und die Aufgabe, Reflexion dieser Kontexte als Context Awareness zu fördern. Context Awareness als Kriterium löst sich von der pädagogischen und didaktischen Engführung der Medienkompetenz. 
            Um sich tragfähigen pädagogischen Antworten anzunähern, ist es wichtig die altbekannten Medien und die neuen digitalen Repräsentationsformen mit Hilfe der Cultural Studies als Signifying Practices zu erschließen. Wichtig war dafür Stuart Hall, 1980, mit seinem Text „Encoding/Decoding“. Hier ist die Frage hilfreich, wie Signifying Practices mit ihren Medien und mit neuen digitalen Repräsentationsformen in unserer Kultur funktionieren. Diese Frage nicht einfach zu beantworten. Beispiel für eine einfache Antwort ist: Handys raus aus der Schule. Weil unsere Kultur wie unsere Gesellschaft disparat aufgebaut ist, also in sich nicht homogen ist, sondern mit Widersprüchen und Brüchen einher geht, sind einfache Antworten keine Lösung der kulturökologisch zu beschreibenden Situation. Zu dieser Situation gehört die Alltäglichkeit von Multimodalität, bei der z.B. alle Varianten von Bildern und Tönen jetzt Text-Funktion bekommen. Gunther Kress‘, 2010, sozialsemiotische Erklärung von Multimodality hat dafür eine Schlüsselfunktion.
            Diese Entwicklungen von Kommunikationskultur sind auch Formen von Entgrenzung, die mit der Entgrenzung von früheren Mediensystemen mit z.B. der redaktionell geleiteten Fernsehanstalten ebenso einher geht wie die Verknüpfung von informellem Lernen des Alltags mit institutionellem Lernen. Hier ist eine wesentliches Thema Mobilität.
        </p>
    </div>
</template>

<script>
export default {
    name: "CulturalEcologyDefinition",
}
</script>